// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class Admin
    {
        public Admin()
        {
            ForgotPasswordToken = new HashSet<ForgotPasswordToken>();
        }

        [Key]
        public long AdminId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [Required]
        [StringLength(101)]
        [Unicode(false)]
        public string FullName { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string EmailAddress { get; set; }
        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string Password { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public long? DeletedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedOn { get; set; }

        [InverseProperty("Admin")]
        public virtual ICollection<ForgotPasswordToken> ForgotPasswordToken { get; set; }
    }
}