// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class BankBSBDirectory
    {
        [Key]
        public int BankBSBDirectoryId { get; set; }
        public int BankId { get; set; }
        [Required]
        [StringLength(50)]
        public string BSBNumber { get; set; }
        [Required]
        [StringLength(500)]
        public string BankStreetAddress { get; set; }
        [Required]
        [StringLength(500)]
        public string City { get; set; }
        [Required]
        [StringLength(500)]
        public string State { get; set; }
        public int PostalCode { get; set; }
        [Required]
        [StringLength(100)]
        public string PEH { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }

        [ForeignKey("BankId")]
        [InverseProperty("BankBSBDirectory")]
        public virtual Bank Bank { get; set; }
    }
}