// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class Bank
    {
        public Bank()
        {
            BankBSBDirectory = new HashSet<BankBSBDirectory>();
        }

        [Key]
        public int BankId { get; set; }
        [Required]
        [StringLength(50)]
        public string BankCode { get; set; }
        [Required]
        [StringLength(250)]
        public string BankName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }

        [InverseProperty("Bank")]
        public virtual ICollection<BankBSBDirectory> BankBSBDirectory { get; set; }
    }
}