// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class Category
    {
        public Category()
        {
            Service = new HashSet<Service>();
        }

        [Key]
        public long CategoryId { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string CategoryCode { get; set; }
        [Required]
        [Unicode(false)]
        public string CategoryName { get; set; }
        [StringLength(350)]
        public string Image { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public long? DeletedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedOn { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<Service> Service { get; set; }
    }
}