// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class Clinic
    {
        [Key]
        public long ClinicId { get; set; }
        public long MerchantId { get; set; }
        [Unicode(false)]
        public string ClinicImage { get; set; }
        [Required]
        [StringLength(500)]
        public string ClinicName { get; set; }
        [StringLength(250)]
        public string ClinicLocation { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
    }
}