// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class CustomerPlans
    {
        public CustomerPlans()
        {
            PlanScheduleDeduction = new HashSet<PlanScheduleDeduction>();
        }

        [Key]
        public long CustomerPlanId { get; set; }
        public long CustomerId { get; set; }
        public long MasterServiceId { get; set; }
        public long MerchantId { get; set; }
        [Required]
        [StringLength(500)]
        public string PlanImage { get; set; }
        [Required]
        [StringLength(50)]
        public string PlanName { get; set; }
        public bool IsActive { get; set; }
        public long? Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        public long CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public bool IsDelete { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        public long? DeletedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedOn { get; set; }

        [ForeignKey("CustomerId")]
        [InverseProperty("CustomerPlans")]
        public virtual Customer Customer { get; set; }
        [ForeignKey("MasterServiceId")]
        [InverseProperty("CustomerPlans")]
        public virtual Service MasterService { get; set; }
        [ForeignKey("MerchantId")]
        [InverseProperty("CustomerPlans")]
        public virtual Merchant Merchant { get; set; }
        [InverseProperty("CustomerPlan")]
        public virtual ICollection<PlanScheduleDeduction> PlanScheduleDeduction { get; set; }
    }
}