// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class Customer
    {
        public Customer()
        {
            CustomerBank = new HashSet<CustomerBank>();
            CustomerCreditCard = new HashSet<CustomerCreditCard>();
            CustomerEmergencyContact = new HashSet<CustomerEmergencyContact>();
            CustomerFamilyMember = new HashSet<CustomerFamilyMember>();
            CustomerForgotPasswordToken = new HashSet<CustomerForgotPasswordToken>();
            CustomerPlans = new HashSet<CustomerPlans>();
        }

        [Key]
        public long CustomerId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string EmailAddress { get; set; }
        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string Password { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal WalletAmount { get; set; }
        public int TotalPlans { get; set; }
        public bool IsActive { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public long? DeletedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedOn { get; set; }
        [Required]
        [StringLength(101)]
        [Unicode(false)]
        public string FullName { get; set; }
        [Required]
        public string StripeId { get; set; }
        [StringLength(350)]
        [Unicode(false)]
        public string ProfilePic { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BirthDate { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string CustomerAddress { get; set; }

        [InverseProperty("Customer")]
        public virtual ICollection<CustomerBank> CustomerBank { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<CustomerCreditCard> CustomerCreditCard { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<CustomerEmergencyContact> CustomerEmergencyContact { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<CustomerFamilyMember> CustomerFamilyMember { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<CustomerForgotPasswordToken> CustomerForgotPasswordToken { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<CustomerPlans> CustomerPlans { get; set; }
    }
}