// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class CustomerBank
    {
        [Key]
        public long CustomerBankId { get; set; }
        public long CustomerId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string AccountNumber { get; set; }
        [Required]
        [StringLength(500)]
        public string BankName { get; set; }
        [Required]
        [StringLength(500)]
        public string BankLocation { get; set; }
        [Required]
        [StringLength(500)]
        public string FullName { get; set; }
        public bool IsVerified { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public long? DeletedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedOn { get; set; }

        [ForeignKey("CustomerId")]
        [InverseProperty("CustomerBank")]
        public virtual Customer Customer { get; set; }
    }
}