// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class CustomerForgotPasswordToken
    {
        [Key]
        public long ForgotPasswordTokenId { get; set; }
        public long? CustomerId { get; set; }
        public Guid Token { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChangedOn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }

        [ForeignKey("CustomerId")]
        [InverseProperty("CustomerForgotPasswordToken")]
        public virtual Customer Customer { get; set; }
    }
}