// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class ForgotPasswordToken
    {
        [Key]
        public long ForgotPasswordTokenId { get; set; }
        public long? AdminId { get; set; }
        public long? MerchantId { get; set; }
        public Guid Token { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChangedOn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }

        [ForeignKey("AdminId")]
        [InverseProperty("ForgotPasswordToken")]
        public virtual Admin Admin { get; set; }
        [ForeignKey("MerchantId")]
        [InverseProperty("ForgotPasswordToken")]
        public virtual Merchant Merchant { get; set; }
    }
}