// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class MerchantBank
    {
        [Key]
        public long MerchantBankId { get; set; }
        public long MerchantId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string BankName { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string BankLocation { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string AccountNumber { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string BSB { get; set; }
        public bool IsVerified { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public long? DeletedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedOn { get; set; }

        [ForeignKey("MerchantId")]
        [InverseProperty("MerchantBank")]
        public virtual Merchant Merchant { get; set; }
    }
}