// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class Merchant
    {
        public Merchant()
        {
            CustomerPlans = new HashSet<CustomerPlans>();
            ForgotPasswordToken = new HashSet<ForgotPasswordToken>();
            MerchantBank = new HashSet<MerchantBank>();
        }

        [Key]
        public long MerchantId { get; set; }
        [Unicode(false)]
        public string ProfilePic { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [Required]
        [StringLength(101)]
        [Unicode(false)]
        public string FullName { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string EmailAddress { get; set; }
        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string Password { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }
        [Unicode(false)]
        public string Logo { get; set; }
        public long CategoryId { get; set; }
        [Required]
        public string ServiceId { get; set; }
        public long ClinicId { get; set; }
        [Required]
        [StringLength(500)]
        public string Notes { get; set; }
        public bool IsActive { get; set; }
        public int? Status { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public bool IsRejected { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public long? DeletedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedOn { get; set; }
        [Required]
        public string StripeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Accepted { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string RejectReason { get; set; }

        [InverseProperty("Merchant")]
        public virtual ICollection<CustomerPlans> CustomerPlans { get; set; }
        [InverseProperty("Merchant")]
        public virtual ICollection<ForgotPasswordToken> ForgotPasswordToken { get; set; }
        [InverseProperty("Merchant")]
        public virtual ICollection<MerchantBank> MerchantBank { get; set; }
    }
}