// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class PlanScheduleDeduction
    {
        [Key]
        public long PSDId { get; set; }
        public long CustomerPlanId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime PSDDate { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
        public long CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public bool IsDelete { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey("CustomerPlanId")]
        [InverseProperty("PlanScheduleDeduction")]
        public virtual CustomerPlans CustomerPlan { get; set; }
    }
}