// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class ServiceDetails
    {
        [Key]
        public long ServiceDetailId { get; set; }
        public long ServiceId { get; set; }
        [Required]
        [StringLength(50)]
        public string Duration { get; set; }
        [Required]
        [StringLength(50)]
        public string Weeks { get; set; }
        [Required]
        [StringLength(100)]
        public string PaymentFrequency { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal PayAmount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [StringLength(50)]
        public string FamilyMemberName { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public bool IsDelete { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey("ServiceId")]
        [InverseProperty("ServiceDetails")]
        public virtual Service Service { get; set; }
    }
}