// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class Service
    {
        public Service()
        {
            CustomerPlans = new HashSet<CustomerPlans>();
            ServiceDetails = new HashSet<ServiceDetails>();
        }

        [Key]
        public long ServiceId { get; set; }
        public long CategoryId { get; set; }
        [Required]
        [Unicode(false)]
        public string ServiceName { get; set; }
        [Required]
        [Unicode(false)]
        public string Description { get; set; }
        [Required]
        [StringLength(350)]
        [Unicode(false)]
        public string Image { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public long? DeletedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedOn { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("Service")]
        public virtual Category Category { get; set; }
        [InverseProperty("MasterService")]
        public virtual ICollection<CustomerPlans> CustomerPlans { get; set; }
        [InverseProperty("Service")]
        public virtual ICollection<ServiceDetails> ServiceDetails { get; set; }
    }
}