// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class TempLayByPlan
    {
        [Key]
        public long LayByPlanID { get; set; }
        [StringLength(350)]
        [Unicode(false)]
        public string Logo { get; set; }
        [StringLength(100)]
        public string Merchant { get; set; }
        [StringLength(100)]
        public string Category { get; set; }
        [StringLength(100)]
        public string Service { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? DurationPrice { get; set; }
        [StringLength(100)]
        public string Customer { get; set; }
        public bool? IsDeleted { get; set; }
    }
}