// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HealthLayby.Models.Models
{
    public partial class TempLayByTransaction
    {
        [Key]
        public long TransactionID { get; set; }
        [StringLength(50)]
        public string TransactionCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [StringLength(100)]
        public string Customer { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? PaidAmount { get; set; }
        [StringLength(50)]
        public string LayByPlan { get; set; }
        public bool? IsDeleted { get; set; }
    }
}