// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace HealthLayby.Models.Models
{
    public partial class TopCustomerGridListResult
    {
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string Registeredon { get; set; }
        public int TotalPlans { get; set; }
        public decimal WalletAmount { get; set; }
    }
}
