// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace HealthLayby.Models.Models
{
    public partial class TopMerchantGridListResult
    {
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Registeredon { get; set; }
        public string Logo { get; set; }
        public string ProfilePic { get; set; }
        public long MerchantId { get; set; }
        public string ServicesNames { get; set; }
    }
}
