// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace HealthLayby.Models.Models
{
    public partial class TopPlanHistoryGridListResult
    {
        public string Customer { get; set; }
        public string PhoneNumber { get; set; }
        public string Merchant { get; set; }
        public decimal Amount { get; set; }
        public string PlanName { get; set; }
        public string Duration { get; set; }
        public string PaymentFrequency { get; set; }
    }
}
