// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace HealthLayby.Models.Models
{
    public partial class TopTransactionGridListResult
    {
        public string TransactionCode { get; set; }
        public string Date { get; set; }
        public string Customer { get; set; }
        public decimal? PaidAmount { get; set; }
        public string LayByPlan { get; set; }
    }
}
