// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HealthLayby.Models.Context;
using HealthLayby.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HealthLayby.Models.Context.Configurations
{
    public partial class BankBSBDirectoryConfiguration : IEntityTypeConfiguration<BankBSBDirectory>
    {
        public void Configure(EntityTypeBuilder<BankBSBDirectory> entity)
        {
            entity.HasOne(d => d.Bank)
                .WithMany(p => p.BankBSBDirectory)
                .HasForeignKey(d => d.BankId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BankBSBDirectory_Bank");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BankBSBDirectory> entity);
    }
}
