// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HealthLayby.Models.Context;
using HealthLayby.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HealthLayby.Models.Context.Configurations
{
    public partial class CustomerForgotPasswordTokenConfiguration : IEntityTypeConfiguration<CustomerForgotPasswordToken>
    {
        public void Configure(EntityTypeBuilder<CustomerForgotPasswordToken> entity)
        {
            entity.HasOne(d => d.Customer)
                .WithMany(p => p.CustomerForgotPasswordToken)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_CustomerForgotPasswordToken_CustomerForgotPasswordToken");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomerForgotPasswordToken> entity);
    }
}
