// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HealthLayby.Models.Context;
using HealthLayby.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HealthLayby.Models.Context.Configurations
{
    public partial class CustomerCreditCardConfiguration : IEntityTypeConfiguration<CustomerCreditCard>
    {
        public void Configure(EntityTypeBuilder<CustomerCreditCard> entity)
        {
            entity.HasKey(e => e.CreditCardId)
                .HasName("PK_CreditCard");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.CustomerCreditCard)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerCreditCard_Customer");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomerCreditCard> entity);
    }
}
