// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HealthLayby.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace HealthLayby.Models.Context.Configurations
{
    public partial class CustomerPlansConfiguration : IEntityTypeConfiguration<CustomerPlans>
    {
        public void Configure(EntityTypeBuilder<CustomerPlans> entity)
        {
            entity.Property(e => e.Status).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.CustomerPlans)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerPlans_Customer");

            entity.HasOne(d => d.MasterService)
                .WithMany(p => p.CustomerPlans)
                .HasForeignKey(d => d.MasterServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerPlans_Service");

            entity.HasOne(d => d.Merchant)
                .WithMany(p => p.CustomerPlans)
                .HasForeignKey(d => d.MerchantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerPlans_Merchant");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomerPlans> entity);
    }
}