// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HealthLayby.Models.Context;
using HealthLayby.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HealthLayby.Models.Context.Configurations
{
    public partial class ForgotPasswordTokenConfiguration : IEntityTypeConfiguration<ForgotPasswordToken>
    {
        public void Configure(EntityTypeBuilder<ForgotPasswordToken> entity)
        {
            entity.HasOne(d => d.Admin)
                .WithMany(p => p.ForgotPasswordToken)
                .HasForeignKey(d => d.AdminId)
                .HasConstraintName("FK_ForgotPasswordToken_Admin");

            entity.HasOne(d => d.Merchant)
                .WithMany(p => p.ForgotPasswordToken)
                .HasForeignKey(d => d.MerchantId)
                .HasConstraintName("FK_ForgotPasswordToken_Merchant");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ForgotPasswordToken> entity);
    }
}
