// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HealthLayby.Models.Context;
using HealthLayby.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HealthLayby.Models.Context.Configurations
{
    public partial class MerchantBankConfiguration : IEntityTypeConfiguration<MerchantBank>
    {
        public void Configure(EntityTypeBuilder<MerchantBank> entity)
        {
            entity.HasOne(d => d.Merchant)
                .WithMany(p => p.MerchantBank)
                .HasForeignKey(d => d.MerchantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKMerchant");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MerchantBank> entity);
    }
}
