// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HealthLayby.Models.Context;
using HealthLayby.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HealthLayby.Models.Context.Configurations
{
    public partial class PlanScheduleDeductionConfiguration : IEntityTypeConfiguration<PlanScheduleDeduction>
    {
        public void Configure(EntityTypeBuilder<PlanScheduleDeduction> entity)
        {
            entity.HasOne(d => d.CustomerPlan)
                .WithMany(p => p.PlanScheduleDeduction)
                .HasForeignKey(d => d.CustomerPlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlanScheduleDeduction_CustomerPlans");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PlanScheduleDeduction> entity);
    }
}
