// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HealthLayby.Models.Context;
using HealthLayby.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HealthLayby.Models.Context.Configurations
{
    public partial class RewardsConfiguration : IEntityTypeConfiguration<Rewards>
    {
        public void Configure(EntityTypeBuilder<Rewards> entity)
        {
            //entity.HasOne(d => d.Category)
            //    .WithMany(p => p.Rewards)
            //    .HasForeignKey(d => d.CategoryId)
            //    .OnDelete(DeleteBehavior.ClientSetNull)
            //    .HasConstraintName("FK_Rewards_Category");

            //entity.HasOne(d => d.Merchant)
            //    .WithMany(p => p.Rewards)
            //    .HasForeignKey(d => d.MerchantId)
            //    .OnDelete(DeleteBehavior.ClientSetNull)
            //    .HasConstraintName("FK_Rewards_Merchant");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Rewards> entity);
    }
}
