// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HealthLayby.Models.Context;
using HealthLayby.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HealthLayby.Models.Context.Configurations
{
    public partial class TempLayByPlanConfiguration : IEntityTypeConfiguration<TempLayByPlan>
    {
        public void Configure(EntityTypeBuilder<TempLayByPlan> entity)
        {
            entity.Property(e => e.LayByPlanID).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TempLayByPlan> entity);
    }
}
